// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (id, upload_id, hls_root, status)
VALUES ($1, $2, $3, $4)
RETURNING id, upload_id, hls_root, status, created_at, updated_at
`

type CreateAssetParams struct {
	ID       pgtype.UUID
	UploadID pgtype.UUID
	HlsRoot  string
	Status   AssetStatus
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ID,
		arg.UploadID,
		arg.HlsRoot,
		arg.Status,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.HlsRoot,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, upload_id, hls_root, status, created_at, updated_at FROM assets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAsset(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.HlsRoot,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetByUploadID = `-- name: GetAssetByUploadID :one
SELECT id, upload_id, hls_root, status, created_at, updated_at FROM assets
WHERE upload_id = $1 LIMIT 1
`

func (q *Queries) GetAssetByUploadID(ctx context.Context, uploadID pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByUploadID, uploadID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.HlsRoot,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssetStatus = `-- name: UpdateAssetStatus :one
UPDATE assets
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, upload_id, hls_root, status, created_at, updated_at
`

type UpdateAssetStatusParams struct {
	ID     pgtype.UUID
	Status AssetStatus
}

func (q *Queries) UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAssetStatus, arg.ID, arg.Status)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.HlsRoot,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
