// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AssetStatus string

const (
	AssetStatusProcessing AssetStatus = "processing"
	AssetStatusReady      AssetStatus = "ready"
	AssetStatusFailed     AssetStatus = "failed"
	AssetStatusDeleted    AssetStatus = "deleted"
)

func (e *AssetStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetStatus(s)
	case string:
		*e = AssetStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetStatus: %T", src)
	}
	return nil
}

type NullAssetStatus struct {
	AssetStatus AssetStatus
	Valid       bool // Valid is true if AssetStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssetStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetStatus), nil
}

type RealmStatus string

const (
	RealmStatusActive  RealmStatus = "active"
	RealmStatusDeleted RealmStatus = "deleted"
)

func (e *RealmStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RealmStatus(s)
	case string:
		*e = RealmStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RealmStatus: %T", src)
	}
	return nil
}

type NullRealmStatus struct {
	RealmStatus RealmStatus
	Valid       bool // Valid is true if RealmStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRealmStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RealmStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RealmStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRealmStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RealmStatus), nil
}

type UploadStatus string

const (
	UploadStatusPending    UploadStatus = "pending"
	UploadStatusUploaded   UploadStatus = "uploaded"
	UploadStatusProcessing UploadStatus = "processing"
	UploadStatusReady      UploadStatus = "ready"
	UploadStatusFailed     UploadStatus = "failed"
	UploadStatusDeleted    UploadStatus = "deleted"
)

func (e *UploadStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UploadStatus(s)
	case string:
		*e = UploadStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UploadStatus: %T", src)
	}
	return nil
}

type NullUploadStatus struct {
	UploadStatus UploadStatus
	Valid        bool // Valid is true if UploadStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUploadStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UploadStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UploadStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUploadStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UploadStatus), nil
}

type Asset struct {
	ID            pgtype.UUID
	UploadID      pgtype.UUID
	RealmID       pgtype.UUID
	HlsRoot       string
	ThumbnailRoot pgtype.Text
	Status        AssetStatus
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type Realm struct {
	ID        pgtype.UUID
	Name      string
	Status    RealmStatus
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Upload struct {
	ID        pgtype.UUID
	RealmID   pgtype.UUID
	Title     string
	S3Key     string
	Status    UploadStatus
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
