// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: realms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRealm = `-- name: CreateRealm :one
INSERT INTO realms (name)
VALUES ($1)
RETURNING id, name, status, created_at, deleted_at
`

func (q *Queries) CreateRealm(ctx context.Context, name string) (Realm, error) {
	row := q.db.QueryRow(ctx, createRealm, name)
	var i Realm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRealm = `-- name: DeleteRealm :exec
UPDATE realms
SET status = 'deleted', deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteRealm(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRealm, id)
	return err
}

const getRealm = `-- name: GetRealm :one
SELECT id, name, status, created_at, deleted_at FROM realms
WHERE id = $1 AND status != 'deleted' LIMIT 1
`

func (q *Queries) GetRealm(ctx context.Context, id pgtype.UUID) (Realm, error) {
	row := q.db.QueryRow(ctx, getRealm, id)
	var i Realm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRealmByName = `-- name: GetRealmByName :one
SELECT id, name, status, created_at, deleted_at FROM realms
WHERE name = $1 AND status != 'deleted' LIMIT 1
`

func (q *Queries) GetRealmByName(ctx context.Context, name string) (Realm, error) {
	row := q.db.QueryRow(ctx, getRealmByName, name)
	var i Realm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listRealms = `-- name: ListRealms :many
SELECT id, name, status, created_at, deleted_at FROM realms
WHERE status != 'deleted'
ORDER BY name ASC
`

func (q *Queries) ListRealms(ctx context.Context) ([]Realm, error) {
	rows, err := q.db.Query(ctx, listRealms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Realm
	for rows.Next() {
		var i Realm
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
