// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: uploads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (id, title, s3_key, status)
VALUES ($1, $2, $3, $4)
RETURNING id, title, s3_key, status, created_at, updated_at
`

type CreateUploadParams struct {
	ID     pgtype.UUID
	Title  string
	S3Key  string
	Status UploadStatus
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, createUpload,
		arg.ID,
		arg.Title,
		arg.S3Key,
		arg.Status,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.S3Key,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUpload = `-- name: GetUpload :one
SELECT id, title, s3_key, status, created_at, updated_at FROM uploads
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUpload(ctx context.Context, id pgtype.UUID) (Upload, error) {
	row := q.db.QueryRow(ctx, getUpload, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.S3Key,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUploads = `-- name: ListUploads :many
SELECT id, title, s3_key, status, created_at, updated_at FROM uploads
ORDER BY created_at DESC
`

func (q *Queries) ListUploads(ctx context.Context) ([]Upload, error) {
	rows, err := q.db.Query(ctx, listUploads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Upload
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.S3Key,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUploadStatusByKey = `-- name: UpdateUploadStatusByKey :one
UPDATE uploads
SET status = $2, updated_at = NOW()
WHERE s3_key = $1
RETURNING id, title, s3_key, status, created_at, updated_at
`

type UpdateUploadStatusByKeyParams struct {
	S3Key  string
	Status UploadStatus
}

func (q *Queries) UpdateUploadStatusByKey(ctx context.Context, arg UpdateUploadStatusByKeyParams) (Upload, error) {
	row := q.db.QueryRow(ctx, updateUploadStatusByKey, arg.S3Key, arg.Status)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.S3Key,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
